import numpy as np
import torch
from torchvision.transforms import functional as F
import math, random
from PIL import Image

aa = torch.tensor([[1, 2], [3, 4]])
bb = torch.stack(
    [
        torch.tensor([[1, 2], [3, 4]]),
        torch.tensor([[1, 2], [3, 4]]),
        torch.tensor([[1, 2], [3, 4]]),
    ]
)
print(bb.shape)

# path = "./data/mvtec/capsule/train/good/004.png"

# resized_image_size = 512
# patch_size = 256
# patch_stride = 128
# images = []

# with open(path, "rb") as f:
#     img = Image.open(f)
#     img.load()
#     myimage = img.convert("RGB")
#     resized_image = myimage.resize((resized_image_size, resized_image_size))
#     top = 0
#     while top + patch_size <= resized_image_size:
#         left = 0
#         while left + patch_size <= resized_image_size:
#             patch = F.crop(resized_image, top, left, patch_size, patch_size)
#             patch.save(f"{top}{left}patch.png")
#             left += patch_stride
#         top += patch_stride


# print(x)
# print(x.sum(dim=1))
# # print(x.shape[-3])
# y = torch.arange(1, 5, 1).view(-1, 1, 1)
# z = x * y
# print(
#     F.normalize(
#         torch.tensor(np.array([[1, 5, 10], [5, 25, 50]]), dtype=torch.float32), dim=0
#     )
# )


# discard "module.encoder_k/projector_k.*" "module.projector.*" and "module.value_transform.*"
lis = [
    "encoder.conv1.weight",
    "encoder.bn1.weight",
    "encoder.bn1.bias",
    "encoder.bn1.running_mean",
    "encoder.bn1.running_var",
    "encoder.bn1.num_batches_tracked",
    "encoder.layer1.0.conv1.weight",
    "encoder.layer1.0.bn1.weight",
    "encoder.layer1.0.bn1.bias",
    "encoder.layer1.0.bn1.running_mean",
    "encoder.layer1.0.bn1.running_var",
    "encoder.layer1.0.bn1.num_batches_tracked",
    "encoder.layer1.0.conv2.weight",
    "encoder.layer1.0.bn2.weight",
    "encoder.layer1.0.bn2.bias",
    "encoder.layer1.0.bn2.running_mean",
    "encoder.layer1.0.bn2.running_var",
    "encoder.layer1.0.bn2.num_batches_tracked",
    "encoder.layer1.1.conv1.weight",
    "encoder.layer1.1.bn1.weight",
    "encoder.layer1.1.bn1.bias",
    "encoder.layer1.1.bn1.running_mean",
    "encoder.layer1.1.bn1.running_var",
    "encoder.layer1.1.bn1.num_batches_tracked",
    "encoder.layer1.1.conv2.weight",
    "encoder.layer1.1.bn2.weight",
    "encoder.layer1.1.bn2.bias",
    "encoder.layer1.1.bn2.running_mean",
    "encoder.layer1.1.bn2.running_var",
    "encoder.layer1.1.bn2.num_batches_tracked",
    "encoder.layer2.0.conv1.weight",
    "encoder.layer2.0.bn1.weight",
    "encoder.layer2.0.bn1.bias",
    "encoder.layer2.0.bn1.running_mean",
    "encoder.layer2.0.bn1.running_var",
    "encoder.layer2.0.bn1.num_batches_tracked",
    "encoder.layer2.0.conv2.weight",
    "encoder.layer2.0.bn2.weight",
    "encoder.layer2.0.bn2.bias",
    "encoder.layer2.0.bn2.running_mean",
    "encoder.layer2.0.bn2.running_var",
    "encoder.layer2.0.bn2.num_batches_tracked",
    "encoder.layer2.0.downsample.0.weight",
    "encoder.layer2.0.downsample.1.weight",
    "encoder.layer2.0.downsample.1.bias",
    "encoder.layer2.0.downsample.1.running_mean",
    "encoder.layer2.0.downsample.1.running_var",
    "encoder.layer2.0.downsample.1.num_batches_tracked",
    "encoder.layer2.1.conv1.weight",
    "encoder.layer2.1.bn1.weight",
    "encoder.layer2.1.bn1.bias",
    "encoder.layer2.1.bn1.running_mean",
    "encoder.layer2.1.bn1.running_var",
    "encoder.layer2.1.bn1.num_batches_tracked",
    "encoder.layer2.1.conv2.weight",
    "encoder.layer2.1.bn2.weight",
    "encoder.layer2.1.bn2.bias",
    "encoder.layer2.1.bn2.running_mean",
    "encoder.layer2.1.bn2.running_var",
    "encoder.layer2.1.bn2.num_batches_tracked",
    "encoder.layer3.0.conv1.weight",
    "encoder.layer3.0.bn1.weight",
    "encoder.layer3.0.bn1.bias",
    "encoder.layer3.0.bn1.running_mean",
    "encoder.layer3.0.bn1.running_var",
    "encoder.layer3.0.bn1.num_batches_tracked",
    "encoder.layer3.0.conv2.weight",
    "encoder.layer3.0.bn2.weight",
    "encoder.layer3.0.bn2.bias",
    "encoder.layer3.0.bn2.running_mean",
    "encoder.layer3.0.bn2.running_var",
    "encoder.layer3.0.bn2.num_batches_tracked",
    "encoder.layer3.0.downsample.0.weight",
    "encoder.layer3.0.downsample.1.weight",
    "encoder.layer3.0.downsample.1.bias",
    "encoder.layer3.0.downsample.1.running_mean",
    "encoder.layer3.0.downsample.1.running_var",
    "encoder.layer3.0.downsample.1.num_batches_tracked",
    "encoder.layer3.1.conv1.weight",
    "encoder.layer3.1.bn1.weight",
    "encoder.layer3.1.bn1.bias",
    "encoder.layer3.1.bn1.running_mean",
    "encoder.layer3.1.bn1.running_var",
    "encoder.layer3.1.bn1.num_batches_tracked",
    "encoder.layer3.1.conv2.weight",
    "encoder.layer3.1.bn2.weight",
    "encoder.layer3.1.bn2.bias",
    "encoder.layer3.1.bn2.running_mean",
    "encoder.layer3.1.bn2.running_var",
    "encoder.layer3.1.bn2.num_batches_tracked",
    "encoder.layer4.0.conv1.weight",
    "encoder.layer4.0.bn1.weight",
    "encoder.layer4.0.bn1.bias",
    "encoder.layer4.0.bn1.running_mean",
    "encoder.layer4.0.bn1.running_var",
    "encoder.layer4.0.bn1.num_batches_tracked",
    "encoder.layer4.0.conv2.weight",
    "encoder.layer4.0.bn2.weight",
    "encoder.layer4.0.bn2.bias",
    "encoder.layer4.0.bn2.running_mean",
    "encoder.layer4.0.bn2.running_var",
    "encoder.layer4.0.bn2.num_batches_tracked",
    "encoder.layer4.0.downsample.0.weight",
    "encoder.layer4.0.downsample.1.weight",
    "encoder.layer4.0.downsample.1.bias",
    "encoder.layer4.0.downsample.1.running_mean",
    "encoder.layer4.0.downsample.1.running_var",
    "encoder.layer4.0.downsample.1.num_batches_tracked",
    "encoder.layer4.1.conv1.weight",
    "encoder.layer4.1.bn1.weight",
    "encoder.layer4.1.bn1.bias",
    "encoder.layer4.1.bn1.running_mean",
    "encoder.layer4.1.bn1.running_var",
    "encoder.layer4.1.bn1.num_batches_tracked",
    "encoder.layer4.1.conv2.weight",
    "encoder.layer4.1.bn2.weight",
    "encoder.layer4.1.bn2.bias",
    "encoder.layer4.1.bn2.running_mean",
    "encoder.layer4.1.bn2.running_var",
    "encoder.layer4.1.bn2.num_batches_tracked",
    "projector.linear1.weight",
    "projector.linear1.bias",
    "projector.bn1.weight",
    "projector.bn1.bias",
    "projector.bn1.running_mean",
    "projector.bn1.running_var",
    "projector.bn1.num_batches_tracked",
    "projector.linear2.weight",
    "projector.linear2.bias",
    "encoder_k.conv1.weight",
    "encoder_k.bn1.weight",
    "encoder_k.bn1.bias",
    "encoder_k.bn1.running_mean",
    "encoder_k.bn1.running_var",
    "encoder_k.bn1.num_batches_tracked",
    "encoder_k.layer1.0.conv1.weight",
    "encoder_k.layer1.0.bn1.weight",
    "encoder_k.layer1.0.bn1.bias",
    "encoder_k.layer1.0.bn1.running_mean",
    "encoder_k.layer1.0.bn1.running_var",
    "encoder_k.layer1.0.bn1.num_batches_tracked",
    "encoder_k.layer1.0.conv2.weight",
    "encoder_k.layer1.0.bn2.weight",
    "encoder_k.layer1.0.bn2.bias",
    "encoder_k.layer1.0.bn2.running_mean",
    "encoder_k.layer1.0.bn2.running_var",
    "encoder_k.layer1.0.bn2.num_batches_tracked",
    "encoder_k.layer1.1.conv1.weight",
    "encoder_k.layer1.1.bn1.weight",
    "encoder_k.layer1.1.bn1.bias",
    "encoder_k.layer1.1.bn1.running_mean",
    "encoder_k.layer1.1.bn1.running_var",
    "encoder_k.layer1.1.bn1.num_batches_tracked",
    "encoder_k.layer1.1.conv2.weight",
    "encoder_k.layer1.1.bn2.weight",
    "encoder_k.layer1.1.bn2.bias",
    "encoder_k.layer1.1.bn2.running_mean",
    "encoder_k.layer1.1.bn2.running_var",
    "encoder_k.layer1.1.bn2.num_batches_tracked",
    "encoder_k.layer2.0.conv1.weight",
    "encoder_k.layer2.0.bn1.weight",
    "encoder_k.layer2.0.bn1.bias",
    "encoder_k.layer2.0.bn1.running_mean",
    "encoder_k.layer2.0.bn1.running_var",
    "encoder_k.layer2.0.bn1.num_batches_tracked",
    "encoder_k.layer2.0.conv2.weight",
    "encoder_k.layer2.0.bn2.weight",
    "encoder_k.layer2.0.bn2.bias",
    "encoder_k.layer2.0.bn2.running_mean",
    "encoder_k.layer2.0.bn2.running_var",
    "encoder_k.layer2.0.bn2.num_batches_tracked",
    "encoder_k.layer2.0.downsample.0.weight",
    "encoder_k.layer2.0.downsample.1.weight",
    "encoder_k.layer2.0.downsample.1.bias",
    "encoder_k.layer2.0.downsample.1.running_mean",
    "encoder_k.layer2.0.downsample.1.running_var",
    "encoder_k.layer2.0.downsample.1.num_batches_tracked",
    "encoder_k.layer2.1.conv1.weight",
    "encoder_k.layer2.1.bn1.weight",
    "encoder_k.layer2.1.bn1.bias",
    "encoder_k.layer2.1.bn1.running_mean",
    "encoder_k.layer2.1.bn1.running_var",
    "encoder_k.layer2.1.bn1.num_batches_tracked",
    "encoder_k.layer2.1.conv2.weight",
    "encoder_k.layer2.1.bn2.weight",
    "encoder_k.layer2.1.bn2.bias",
    "encoder_k.layer2.1.bn2.running_mean",
    "encoder_k.layer2.1.bn2.running_var",
    "encoder_k.layer2.1.bn2.num_batches_tracked",
    "encoder_k.layer3.0.conv1.weight",
    "encoder_k.layer3.0.bn1.weight",
    "encoder_k.layer3.0.bn1.bias",
    "encoder_k.layer3.0.bn1.running_mean",
    "encoder_k.layer3.0.bn1.running_var",
    "encoder_k.layer3.0.bn1.num_batches_tracked",
    "encoder_k.layer3.0.conv2.weight",
    "encoder_k.layer3.0.bn2.weight",
    "encoder_k.layer3.0.bn2.bias",
    "encoder_k.layer3.0.bn2.running_mean",
    "encoder_k.layer3.0.bn2.running_var",
    "encoder_k.layer3.0.bn2.num_batches_tracked",
    "encoder_k.layer3.0.downsample.0.weight",
    "encoder_k.layer3.0.downsample.1.weight",
    "encoder_k.layer3.0.downsample.1.bias",
    "encoder_k.layer3.0.downsample.1.running_mean",
    "encoder_k.layer3.0.downsample.1.running_var",
    "encoder_k.layer3.0.downsample.1.num_batches_tracked",
    "encoder_k.layer3.1.conv1.weight",
    "encoder_k.layer3.1.bn1.weight",
    "encoder_k.layer3.1.bn1.bias",
    "encoder_k.layer3.1.bn1.running_mean",
    "encoder_k.layer3.1.bn1.running_var",
    "encoder_k.layer3.1.bn1.num_batches_tracked",
    "encoder_k.layer3.1.conv2.weight",
    "encoder_k.layer3.1.bn2.weight",
    "encoder_k.layer3.1.bn2.bias",
    "encoder_k.layer3.1.bn2.running_mean",
    "encoder_k.layer3.1.bn2.running_var",
    "encoder_k.layer3.1.bn2.num_batches_tracked",
    "encoder_k.layer4.0.conv1.weight",
    "encoder_k.layer4.0.bn1.weight",
    "encoder_k.layer4.0.bn1.bias",
    "encoder_k.layer4.0.bn1.running_mean",
    "encoder_k.layer4.0.bn1.running_var",
    "encoder_k.layer4.0.bn1.num_batches_tracked",
    "encoder_k.layer4.0.conv2.weight",
    "encoder_k.layer4.0.bn2.weight",
    "encoder_k.layer4.0.bn2.bias",
    "encoder_k.layer4.0.bn2.running_mean",
    "encoder_k.layer4.0.bn2.running_var",
    "encoder_k.layer4.0.bn2.num_batches_tracked",
    "encoder_k.layer4.0.downsample.0.weight",
    "encoder_k.layer4.0.downsample.1.weight",
    "encoder_k.layer4.0.downsample.1.bias",
    "encoder_k.layer4.0.downsample.1.running_mean",
    "encoder_k.layer4.0.downsample.1.running_var",
    "encoder_k.layer4.0.downsample.1.num_batches_tracked",
    "encoder_k.layer4.1.conv1.weight",
    "encoder_k.layer4.1.bn1.weight",
    "encoder_k.layer4.1.bn1.bias",
    "encoder_k.layer4.1.bn1.running_mean",
    "encoder_k.layer4.1.bn1.running_var",
    "encoder_k.layer4.1.bn1.num_batches_tracked",
    "encoder_k.layer4.1.conv2.weight",
    "encoder_k.layer4.1.bn2.weight",
    "encoder_k.layer4.1.bn2.bias",
    "encoder_k.layer4.1.bn2.running_mean",
    "encoder_k.layer4.1.bn2.running_var",
    "encoder_k.layer4.1.bn2.num_batches_tracked",
    "projector_k.linear1.weight",
    "projector_k.linear1.bias",
    "projector_k.bn1.weight",
    "projector_k.bn1.bias",
    "projector_k.bn1.running_mean",
    "projector_k.bn1.running_var",
    "projector_k.bn1.num_batches_tracked",
    "projector_k.linear2.weight",
    "projector_k.linear2.bias",
    "value_transform.weight",
    "value_transform.bias",
    "projector_instance.linear1.weight",
    "projector_instance.linear1.bias",
    "projector_instance.bn1.weight",
    "projector_instance.bn1.bias",
    "projector_instance.bn1.running_mean",
    "projector_instance.bn1.running_var",
    "projector_instance.bn1.num_batches_tracked",
    "projector_instance.linear2.weight",
    "projector_instance.linear2.bias",
    "projector_instance_k.linear1.weight",
    "projector_instance_k.linear1.bias",
    "projector_instance_k.bn1.weight",
    "projector_instance_k.bn1.bias",
    "projector_instance_k.bn1.running_mean",
    "projector_instance_k.bn1.running_var",
    "projector_instance_k.bn1.num_batches_tracked",
    "projector_instance_k.linear2.weight",
    "projector_instance_k.linear2.bias",
    "predictor.linear1.weight",
    "predictor.linear1.bias",
    "predictor.bn1.weight",
    "predictor.bn1.bias",
    "predictor.bn1.running_mean",
    "predictor.bn1.running_var",
    "predictor.bn1.num_batches_tracked",
    "predictor.linear2.weight",
    "predictor.linear2.bias",
]
